In [2]:
import pandas as pd
df = pd.read_csv('spam.csv')
df = df[['v1','v2']]
df[['label','messages']] = df[['v1','v2']]
df = df.drop(['v1','v2'], axis=1)
df.head()

label                                           messages
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [3]:
import re
import nltk
nltk.download('stopwords') 

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\pwal9\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [4]:
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()


In [5]:
corpus = []
stop = set(stopwords.words('english'))
for i in range(len(df)):
    ne = re.sub('[^A-Za-z]', ' ', df['messages'][i])
    ne = ne.lower()
    ne = ne.split()
    ne1 = []
    for word in ne:
        if word not in stop:
            ne1.append(word)
    
    singles = [ps.stem(plural) for plural in ne1]
    singles = ' '.join(singles)
    corpus.append(singles)


In [6]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=2500, ngram_range=(1,2))


In [7]:
x = cv.fit_transform(corpus).toarray()
x

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [8]:
cv.vocabulary_

{'go': np.int64(801),
 'point': np.int64(1608),
 'crazi': np.int64(452),
 'avail': np.int64(117),
 'bugi': np.int64(227),
 'great': np.int64(854),
 'world': np.int64(2437),
 'la': np.int64(1097),
 'cine': np.int64(344),
 'got': np.int64(845),
 'wat': np.int64(2347),
 'ok': np.int64(1476),
 'lar': np.int64(1110),
 'joke': np.int64(1053),
 'wif': np.int64(2403),
 'free': np.int64(722),
 'entri': np.int64(620),
 'wkli': np.int64(2427),
 'comp': np.int64(400),
 'win': np.int64(2408),
 'cup': np.int64(466),
 'final': np.int64(690),
 'st': np.int64(1964),
 'may': np.int64(1264),
 'text': np.int64(2082),
 'receiv': np.int64(1708),
 'question': np.int64(1674),
 'std': np.int64(1980),
 'txt': np.int64(2206),
 'rate': np.int64(1687),
 'appli': np.int64(80),
 'free entri': np.int64(727),
 'entri wkli': np.int64(622),
 'std txt': np.int64(1981),
 'txt rate': np.int64(2212),
 'rate appli': np.int64(1689),
 'dun': np.int64(577),
 'say': np.int64(1805),
 'earli': np.int64(586),
 'alreadi': np.int64(4

In [32]:
y = pd.get_dummies(df['label']).astype(int)

In [33]:
y = y.iloc[:,0].values
y

array([1, 1, 0, ..., 1, 1, 1])

In [11]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest = train_test_split(x,y,test_size=0.20,random_state=20)

In [12]:
from sklearn.naive_bayes import MultinomialNB
spam_detect = MultinomialNB().fit(xtrain,ytrain)

In [13]:
ypreds = spam_detect.predict(xtest)

In [14]:
from sklearn.metrics import accuracy_score, classification_report

accuracy_score(ytest,ypreds)

0.9820627802690582

In [15]:
print(classification_report(ytest,ypreds))

              precision    recall  f1-score   support

           0       0.94      0.92      0.93       148
           1       0.99      0.99      0.99       967

    accuracy                           0.98      1115
   macro avg       0.97      0.96      0.96      1115
weighted avg       0.98      0.98      0.98      1115



In [16]:
xtest

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [70]:
custom_text = ['subscribe and earn']
x_custom = cv.transform(custom_text).toarray()

In [71]:
predicted = spam_detect.predict(x_custom)
predicted

array([1])